# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 54.211.166.118
  become: yes

  tasks:

- name: Call Roles
  hosts: 54.211.166.118
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
