# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 172.31.81.135
  become: yes

  tasks:

- name: Call Roles
  hosts: server
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
