# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: server
  become: yes

  tasks:

- name: Call Roles
  hosts: server
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
