-
  name: Deploying nginx webserver
  hosts: 172.31.80.199
  become: yes
  tasks:
    - name: Install nginx latest version and start service
      apt:
       name: nginx
       state: latest
    - name: Start nginx service
      ansible.builtin.service:
       name: nginx
       state: started

- name: Call Roles
  hosts: 172.31.80.199
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
