- 
  name : install tomcat server
  remote_user: ec2-user
  hosts: apache_nodes
  become: true
  become_method: sudo
  vars_files:
    - tomcat_vars
    
  tasks:
  - name: install java
    yum:
      name: java
      state: latest
       
  - name: dowmload tomcat server packages
    get_url:
      url: "{{ tomcat_url }}"
      dest: /usr/local
       
  - name: extract tomcat packages
    unarchive:
      src: /usr/local{{ tomcat_package }}.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local{{ tomcat_package }}/bin/startup.sh
      
      
