- hosts: 172.31.95.165
  remote_user: ec2-user
  become: yes
  become_method: sudo
  vars:
    - tomcat_url: http://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    - tomcat_package: apache-tomcat-10.0.20
    
  tasks:
  - name: install java
    yum:
      name: java
      state: latest
       
  - name: download tomcat server packages
    get_url:
      url: "{{ tomcat_url }}"
      dest: /usr/local
       
  - name: extract tomcat packages
    unarchive:
      src: /usr/local/{{ tomcat_package }}.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/{{ tomcat_package }}/bin/startup.sh
      
      
